- project:
    name: openstack/mixmatch
    check:
      jobs:
        - mixmatch-dsvm-functional:
            voting: false

- job:
    name: mixmatch-dsvm-functional
    parent: legacy-dsvm-base
    vars:
      test_results_dir: "src/{{ zuul.project.canonical_name }}"
    run: playbooks/legacy/mixmatch-dsvm-functional/run.yaml
    post-run: playbooks/legacy/mixmatch-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/mixmatch

