- project:
    check:
      jobs:
        - mixmatch-dsvm-functional-compute:
            voting: false
        - mixmatch-dsvm-functional-image:
            voting: false
        - mixmatch-dsvm-functional-volume:
            voting: false
        - mixmatch-dsvm-functional-network:
            voting: false
        - mixmatch-dsvm-functional-scenario:
            voting: false

        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
- job:
    name: mixmatch-dsvm-functional-base
    parent: legacy-dsvm-base
    run: playbooks/legacy/mixmatch-dsvm-functional/run.yaml
    post-run: playbooks/legacy/mixmatch-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/mixmatch

- job:
    name: mixmatch-dsvm-functional-compute
    parent: mixmatch-dsvm-functional-base
    vars:
      tempest_regex: "^tempest.api.compute"

- job:
    name: mixmatch-dsvm-functional-image
    parent: mixmatch-dsvm-functional-base
    vars:
      tempest_regex: "^tempest.api.image"

- job:
    name: mixmatch-dsvm-functional-volume
    parent: mixmatch-dsvm-functional-base
    vars:
      tempest_regex: "^tempest.api.volume"

- job:
    name: mixmatch-dsvm-functional-network
    parent: mixmatch-dsvm-functional-base
    vars:
      tempest_regex: "^tempest.api.network"

- job:
    name: mixmatch-dsvm-functional-scenario
    parent: mixmatch-dsvm-functional-base
    vars:
      tempest_regex: "^tempest.api.scenario"
