- project:
    templates:
      - openstack-lower-constraints-jobs
    check:
      jobs:
        - mixmatch-dsvm-functional-compute:
            voting: false
        - mixmatch-dsvm-functional-image-volume-network-scenario:
            voting: false

- job:
    name: mixmatch-dsvm-functional-base
    parent: legacy-dsvm-base
    run: playbooks/legacy/mixmatch-dsvm-functional/run.yaml
    post-run: playbooks/legacy/mixmatch-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/mixmatch

- job:
    name: mixmatch-dsvm-functional-compute
    parent: mixmatch-dsvm-functional-base
    vars:
      tempest_regex: "^tempest.api.compute"

- job:
    name: mixmatch-dsvm-functional-image-volume-network-scenario
    parent: mixmatch-dsvm-functional-base
    vars:
      tempest_regex: "(^tempest.api.image|^tempest.api.volume|^tempest.api.network|^tempest.scenario)"
