- project:
    name: openstack/mixmatch
    check:
      jobs:
        - mixmatch-dsvm-func-scenario:
            voting: true
        - mixmatch-dsvm-func-compute-image:
            voting: true
        - mixmatch-dsvm-func-network-volume:
            voting: true

- job:
    name: mixmatch-dsvm-func-scenario
    parent: legacy-dsvm-base
    run: playbooks/legacy/mixmatch-dsvm-functional/run_scenario
    post-run: playbooks/legacy/mixmatch-dsvm-functional/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/mixmatch

- job:
    name: mixmatch-dsvm-func-compute-image
    parent: legacy-dsvm-base
    run: playbooks/legacy/mixmatch-dsvm-functional/run_compute_and_image
    post-run: playbooks/legacy/mixmatch-dsvm-functional/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/mixmatch

- job:
    name: mixmatch-dsvm-func-network-volume
    parent: legacy-dsvm-base
    run: playbooks/legacy/mixmatch-dsvm-functional/run_network_and_volume
    post-run: playbooks/legacy/mixmatch-dsvm-functional/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/mixmatch
