- project:
    name: openstack/mixmatch
    check:
      jobs:
        - mixmatch-dsvm-functional:
            voting: true

- job:
    name: mixmatch-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/mixmatch-dsvm-functional/run
    post-run: playbooks/legacy/mixmatch-dsvm-functional/post
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/mixmatch

